apply plugin: 'com.android.application'

android {
    namespace 'com.sisu.dns'
    compileSdk 34

    defaultConfig {
        applicationId "com.sisu.dns"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
